# Generated by Django 3.2 on 2022-07-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
