# Generated by Django 3.2 on 2022-07-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_modelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelos',
            name='description',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelos',
            name='imagenes',
            field=models.ImageField(upload_to=''),
        ),
    ]
