# Generated by Django 3.2 on 2022-07-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20220727_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelos',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
