# Generated by Django 3.2 on 2022-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_modelos_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Modelos',
        ),
    ]
