# Generated by Django 3.2 on 2022-07-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20220727_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='description',
            field=models.TextField(default=255, max_length=255),
            preserve_default=False,
        ),
    ]
