# Generated by Django 3.2 on 2022-07-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_principal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='predictivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.predictivo'),
        ),
    ]
