# Generated by Django 3.2 on 2022-08-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_principal_predictivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='principal',
            name='predictivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.predictivo'),
        ),
    ]
