# Generated by Django 3.2 on 2022-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20220802_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo_modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_campo', models.CharField(max_length=30)),
                ('info', models.TextField(max_length=255)),
                ('n_campo', models.FloatField(blank=True, null=True)),
                ('ml_model', models.CharField(max_length=30)),
            ],
        ),
    ]
