# Generated by Django 3.2 on 2022-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_predictivo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo_modelo',
            name='option',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
