# Generated by Django 3.2 on 2022-09-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_alter_campo_modelo_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='curriculum',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
