# Generated by Django 3.2 on 2022-09-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_alter_principal_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo_modelo',
            name='option',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
