# Generated by Django 3.2 on 2022-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_alter_campo_modelo_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo_modelo',
            name='notebook_model',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
