# Generated by Django 4.1.1 on 2022-09-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_auto_20220918_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
