# Generated by Django 4.1.1 on 2022-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_remove_principal_curriculum_personaldata_curriculum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='notebook_model',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
